from extensions import db

class MenuCategory(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True, nullable=False)
    display_name = db.Column(db.String(50), nullable=False)
    order = db.Column(db.Integer, nullable=False)
    is_drink_category = db.Column(db.Boolean, default=False)
    items = db.relationship('MenuItem', backref='category', lazy=True)

class MenuItem(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    description = db.Column(db.Text)
    price = db.Column(db.Float, nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('menu_category.id'), nullable=False)
    image_path = db.Column(db.String(255))
    order = db.Column(db.Integer, default=0)
    is_available = db.Column(db.Boolean, default=True)
    is_lunch_special = db.Column(db.Boolean, default=False)
    vegetarian = db.Column(db.Boolean, default=False)
    vegan = db.Column(db.Boolean, default=False)
    spicy = db.Column(db.Boolean, default=False)
    gluten_free = db.Column(db.Boolean, default=False)
    lactose_free = db.Column(db.Boolean, default=False)
    kid_friendly = db.Column(db.Boolean, default=False)
    alcohol_free = db.Column(db.Boolean, default=False)
    contains_alcohol = db.Column(db.Boolean, default=False)
    homemade = db.Column(db.Boolean, default=False)
    sugar_free = db.Column(db.Boolean, default=False)
    recommended = db.Column(db.Boolean, default=False)